export LIBTORCH_ROOT="PATH_TO_LIBTORCH"
export TOKENIZER_ROOT="PATH_TO_TOKENIZER"
export OPENVINO_ROOT="PATH_TO_OPENVINO"
source $OPENVINO_ROOT/setupvars.sh

export LIBTORCH_HEADER="${LIBTORCH_ROOT}/include"
export LIBTORCH_HEADER_CSRC="${LIBTORCH_HEADER}/torch/csrc/api/include"
export TOKENIZER_HEADER="${TOKENIZER_ROOT}/include"
export OPENVINO_HEADER="${OPENVINO_ROOT}/runtime/include"

export LIBTORCH_LIB="${LIBTORCH_ROOT}/lib"
export TOKENIZER_LIB="${TOKENIZER_ROOT}/example/build/tokenizers"
export OPENVINO_LIB="${OPENVINO_ROOT}/runtime/lib/intel64"

# Update PATH and LD_LIBRARY_PATH
export PATH="${TOKENIZER_HEADER}:${LIBTORCH_HEADER}:${OPENVINO_HEADER}:${LIBTORCH_HEADER_CSRC}:${PATH}"
export LD_LIBRARY_PATH="${OPENVINO_LIB}:${LIBTORCH_LIB}:${TOKENIZER_LIB}:${LD_LIBRARY_PATH}"
export PKG_CONFIG_PATH=$OPENVINO_ROOT/runtime/lib/intel64/pkgconfig:$PKG_CONFIG_PATH